export const Menu = {
  URL_LECTURE_PAGE: "/lecture",
  URL_STUDENT_PAGE: "/",
  URL_MOCK_TEST_PAGE: "/mocktest",
  URL_FLASH_CARD_PAGE: "/flashcard",
  URL_CLASSES_PAGE: "/classes",
  URL_ENROLL_PAGE: "/enroll",
  URL_UPLOAD_SOURCE_PAGE: "/upload-source",
  URL_SPEAKING_PAGE: "/speaking",
  URL_SPEAKING_TEST_PAGE: "/speaking-test",
  URL_LOGIN_PAGE: "/login",
  URL_WORD_GAME_PAGE: "/word-game",
  URL_CROSS_GAME_PAGE: "/word-cross-game",
  URL_BOARD_GAME_PAGE: "/games",
  URL_CREATE_FLASHCARD_PAGE: "/create-flashcards",
  URL_VIEW_RESOURCES: "/resources",
};
